version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: lanranginx
    ports:
      - "8800:80"
    volumes:
      - ./project:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - larapphel
      - db

  #Database Service
  db:
    image : mariadb
    container_name : laradbms
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      MYSQL_DATABASE: projectbase
      MYSQL_ROOT_PASSWORD: 'H16lyCla55!fied'
      MYSQL_USER: projectuser
      MYSQL_PASSWORD: 'project#53Cret'  

  # Application Service
  larapphel:
    container_name: laravels
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./project:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laradbadmin
    ports:
      - "8600:80"
    depends_on:
      - db

